name: Changelog generator and NuGet Releasing

on: 
  push:
    tags:
      - '*'
      
jobs:
  changelog-generator:
    runs-on: ubuntu-latest
    env:
      TagOnMaster: false
      Branch: master
    steps:
    - uses: actions/checkout@v1
    - name: Set local user
      run: |
        git config --local user.email "devteam@thecogworks.com"
        git config --local user.name "cogworks-infrastructure"
    - name: Checkout to master from current head
      run: |
        git checkout master
        git pull "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" master
    - name: Checking if hotfix applied to master
      run: |
        HotFixOnMaster=$(git branch --contains refs/tags/`basename $GITHUB_REF` | sed 's/remotes\/origin\///' | sed 's/* //' | grep master)

        if [[ "$HotFixOnMaster" == *"master"* ]]; then
          echo ::set-env name=TagOnMaster::true
        fi
      continue-on-error: true
    - name: Set branch variable
      if: env.TagOnMaster == 'false' || env.TagOnMaster == 0
      run: echo ::set-env name=Branch::$(git branch -a --contains refs/tags/`basename $GITHUB_REF` | sed 's/remotes\/origin\///' | sed 's/master//' | sed 's/* //' | grep release/`basename $GITHUB_REF`)
    - name: Checkout to branch
      run: |
        echo Branch: $Branch
        git checkout $Branch
    - name: Check the tag
      run: git describe --exact-match `git rev-parse HEAD`
    - name: Get tag
      run: echo ::set-env name=Tag::$(git describe --exact-match `git rev-parse HEAD`)
    - name: Install dependencies
      run: |
        rm -rf node_modules
        npm install
    - name: Generate changelog and update npm version
      run: npm run release
    - name: Remove tag
      run: git tag -d $Tag
    - name: Updating tags
      run: |
        git pull "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" master
        git tag -a $Tag -m "$Tag"
        git push "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --tag -f
    - name: Pushing latest changes to master
      run: |
        git pull "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" master
        git push "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" $Branch:master

    - name: Deleting release branch
      if: env.TagOnMaster == 'false' || env.TagOnMaster == 0
      run: git push "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --delete $Branch

    - name: Create file status_changelog-generator.txt and write the job status into it
      if: always()
      run: echo ${{ job.status }} > status_changelog-generator.txt
    - name: Upload file status_changelog-generator.txt as an artifact
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: pass_status_changelog-generator
        path: status_changelog-generator.txt

  updating-branches:
    needs: changelog-generator
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set local user
      run: |
        git config --local user.email "devteam@thecogworks.com"
        git config --local user.name "cogworks-infrastructure"
    - name: Checkout develop and pull latest develop
      run: |
        git checkout develop
        git pull "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" develop
    - name: Pull master into develop
      run: |
        Conflicts=$(git pull "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" master -q --ff-only || echo "fatal: Not possible to fast-forward, aborting")
        AbortingMsg='aborting'

        if [[ "$Conflicts" == *"$AbortingMsg"* ]]; then
          exit 1
        fi
    - name: Pushing develop to origin if pulling successfully
      if: success()
      run: git push "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" develop:develop
    
    - name: Create file status_updating-branches.txt and write the job status into it
      if: always()
      run: echo ${{ job.status }} > status_updating-branches.txt
    - name: Upload file status_updating-branches.txt as an artifact
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: pass_status_updating-branches
        path: status_updating-branches.txt

  nuget-release:
    needs: changelog-generator
    runs-on: windows-latest
    env:
      # Dotnet Setup
      DOTNET_VERSION: 3.1.401

      # Stop wasting time caching packages
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

      # Disable sending usage data to Microsoft
      DOTNET_CLI_TELEMETRY_OPTOUT: true

      # Nuget Setup
      NUGET_VERSION: 'latest'

      # Solution Setup
      CONFIG: 'Release'
      SOLUTION: 'Cogworks.AzureSearch.sln'

      # Project names to pack and publish
      AZURE_SEARCH_PROJECT: Cogworks.AzureSearch
      AZURE_SEARCH_UMBRACO_PROJECT: Cogworks.AzureSearch.Umbraco.IocExtension
      AZURE_SEARCH_LIGHTINJECT_PROJECT: Cogworks.AzureSearch.LightInject.IocExtension
      AZURE_SEARCH_AUTOFAC_PROJECT: Cogworks.AzureSearch.Autofac.IocExtension
      NUGET_OUTPUT: output

      # GitHub Packages Feed settings
      GITHUB_USER: cogworks-infrastructure
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_FEED: https://nuget.pkg.github.com/thecogworks

      # Official NuGet Feed settings
      NUGET_FEED: https://api.nuget.org/v3/index.json
      NUGET_KEY: ${{ secrets.NUGET_KEY }}

    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
        with:
            ref: master

      - name: Set Version based on tag
        shell: bash
        run: echo ::set-env name=VERSION::$(basename $GITHUB_REF)

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 

      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: ${{ env.NUGET_VERSION }} 
        
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            nuget-${{ runner.os }}
            nuget-
            nuget

      - name: NuGet Restore
        run: nuget restore ${{ env.SOLUTION }} -LockedMode

      - name: Install dependencies
        run: dotnet restore ${{env.SOLUTION}}
      
      - name: Build
        working-directory: ${{ github.workspace }}  
        run: dotnet build --configuration ${{ env.CONFIG }} ${{ env.SOLUTION }}

      - name: Pack ${{ env.AZURE_SEARCH_PROJECT }}
        run: nuget pack .\src\${{ env.AZURE_SEARCH_PROJECT }}\${{ env.AZURE_SEARCH_PROJECT }}.nuspec -Version ${{ env.VERSION }} -Properties Configuration=${{ env.CONFIG }} -OutputDirectory .\${{ env.NUGET_OUTPUT }}

      - name: Pack ${{ env.AZURE_SEARCH_UMBRACO_PROJECT }}
        run: nuget pack .\src\${{ env.AZURE_SEARCH_UMBRACO_PROJECT }}\${{ env.AZURE_SEARCH_UMBRACO_PROJECT }}.nuspec -Version ${{ env.VERSION }} -Properties Configuration=${{ env.CONFIG }} -OutputDirectory .\${{ env.NUGET_OUTPUT }}

      - name: Pack ${{ env.AZURE_SEARCH_LIGHTINJECT_PROJECT }}
        run: nuget pack .\src\${{ env.AZURE_SEARCH_LIGHTINJECT_PROJECT }}\${{ env.AZURE_SEARCH_LIGHTINJECT_PROJECT }}.nuspec -Version ${{ env.VERSION }} -Properties Configuration=${{ env.CONFIG }} -OutputDirectory .\${{ env.NUGET_OUTPUT }}

      - name: Pack ${{ env.AZURE_SEARCH_AUTOFAC_PROJECT }}
        run: nuget pack .\src\${{ env.AZURE_SEARCH_AUTOFAC_PROJECT }}\${{ env.AZURE_SEARCH_AUTOFAC_PROJECT }}.nuspec -Version ${{ env.VERSION }} -Properties Configuration=${{ env.CONFIG }} -OutputDirectory .\${{ env.NUGET_OUTPUT }}

      - name: Push to GitHub Feed
        shell: bash
        run: |
          for f in ./${{ env.NUGET_OUTPUT }}/*.nupkg
          do
            curl -vX PUT -u "$GITHUB_USER:$GITHUB_TOKEN" -F package=@$f $GITHUB_FEED
          done

      - name: Push to NuGet Feed
        run: dotnet nuget push .\${{ env.NUGET_OUTPUT }}\*.nupkg --source ${{ env.NUGET_FEED }} --skip-duplicate --api-key ${{ env.NUGET_KEY }}
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: ${{ env.NUGET_OUTPUT }}\*.nupkg

  finalization-and-notification:
    needs: [changelog-generator, updating-branches]
    if: always()
    runs-on: ubuntu-latest
    env:
      Failure: "Failure"
      Success: "Success"
    steps:
      - name: Download artifact pass_status_changelog-generator
        uses: actions/download-artifact@v1
        with:
          name: pass_status_changelog-generator
        continue-on-error: true

      - name: Download artifact pass_status_updating-branches
        uses: actions/download-artifact@v1
        with:
          name: pass_status_updating-branches
        continue-on-error: true

      - name: Set the statuses of jobs
        id: set_outputs
        run: |
          if [ -f "pass_status_changelog-generator/status_changelog-generator.txt" ]; then
           echo "::set-output name=status_changelog-generator::$(<pass_status_changelog-generator/status_changelog-generator.txt)"
          else
            echo "::set-output name=status_changelog-generator::$(echo $Failure)"
          fi

          if [ -f "pass_status_updating-branches/status_updating-branches.txt" ]; then
           echo "::set-output name=status_updating-branches::$(<pass_status_updating-branches/status_updating-branches.txt)"
          else
            echo "::set-output name=status_updating-branches::$(echo $Failure)"
          fi      

      - name: (changelog-generator) Slack notification (successfully tag updated and pushed to master branch)
        if: steps.set_outputs.outputs.status_changelog-generator == env.Success
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_TITLE: 'Release created:'
          SLACK_MESSAGE: "Tag was created and pushed to master branch."
          SLACK_USERNAME: 'Release manager'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        continue-on-error: true

      - name: (changelog-generator) Slack notification (release could not be created)
        if: steps.set_outputs.outputs.status_changelog-generator == env.Failure
        uses: rtCamp/action-slack-notify@master      
        env:
          SLACK_TITLE: 'Release could not be created:'
          SLACK_MESSAGE: "Please log in to Github and check why release couldn't be created."
          SLACK_USERNAME: 'Release manager'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        continue-on-error: true

      - name: (updating-branches) Slack notification (Successfully pulled master into develop)
        if: steps.set_outputs.outputs.status_updating-branches == env.Success
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_TITLE: 'Pull succeeded:'
          SLACK_MESSAGE: "Successfully pulled master into develop"
          SLACK_USERNAME: 'Release manager'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        continue-on-error: true

      - name: (updating-branches) Slack notification (Failed on pulling master into develop)
        if: steps.set_outputs.outputs.status_updating-branches == env.Failure
        uses: rtCamp/action-slack-notify@master      
        env:
          SLACK_TITLE: 'Pull failed'
          SLACK_MESSAGE: "Failed on pulling master into develop"
          SLACK_USERNAME: 'Release manager'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        continue-on-error: true 

      - name: Jobs status finalization
        if: always()
        run: |
          if [[ "${{ steps.set_outputs.outputs.status_changelog-generator }}" == $Failure ]]; then
            exit 1
          fi

          if [[ "${{ steps.set_outputs.outputs.status_updating-branches }}" == $Failure ]]; then
            exit 1
          fi
